name: main

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - run: pnpm install

      - run: pnpm run ci:format

      - run: pnpm run ci:lint

      - run: pnpm --filter "@ukwehuwehneke/ohutsya" build

      - run: pnpm --filter "@ukwehuwehneke/language-components" build

      - run: pnpm run test --filter "learn-oneida-v2"
